apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: test01
  name: demo-spring
  annotations:
    orgs.k8s.snyk.io/v1: e4f1aaec-ce69-479f-987c-5bed92f7b1a8
  labels:
    app: demo-spring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-spring
  template:
    metadata:
      labels:
        app: demo-spring
    spec:
      containers:
        - name: demo-spring
          image: dylansnyk/demo-spring:latest
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: test01
  name: demo-spring-service
spec:
  selector:
    app: demo-spring
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30003