version: 2.1
orbs: 
  snyk: snyk/snyk@2.2.0

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - run: mvn install
      - snyk-scan

workflows:
  build-test-snyk:
    jobs:
      - snyk-scan
