name: Snyk Code

on:
  push:
    branches: [ develop, release ]

jobs:
  snyk-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      
      - name: Download snyk-to-html
      - run: |
          curl -Lo ./snyk-to-html \
          chmod +x snyk-to-html
      
      - uses: snyk/actions/setup@master
      - name: Run Snyk Code to check for vulnerabilities
        run: snyk code test --sarif | ./snyk-to-html -o results.html
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
      - uses: actions/upload-artifact@v3
      - name: Upload Snyk Code Results
        with:
          name: snyk-code-results
          path: results.html
